# Cloud Build configuration file
steps:
  # Install dependencies with caching
  - name: 'node:18-slim'
    entrypoint: npm
    args: ['ci']
    id: 'install'
    waitFor: ['-']

  # Run tests in CI mode
  - name: 'node:18-slim'
    entrypoint: npm
    args: ['test', '--ci', '--passWithNoTests']
    id: 'test'
    waitFor: ['install']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--cache-from', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:latest',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:latest',
      '.'
    ]
    id: 'build'
    waitFor: ['test']

  # Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '--all-tags',
      '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}'
    ]
    id: 'push'
    waitFor: ['build']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      '${_SERVICE_NAME}',
      '--image', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
    id: 'deploy'
    waitFor: ['push']

substitutions:
  _REGION: asia-northeast1
  _REPOSITORY: cloud-native-guide
  _IMAGE: app
  _SERVICE_NAME: cloud-native-guide

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Set build timeout to 20 minutes
timeout: 1200s
